import type { Property } from "./types";

/**
 * DEMO / EXAMPLE PROPERTIES
 * ─────────────────────────
 * Every record below is fictional. Addresses use German placeholder words
 * ("Musterstraße" = "sample street", "Beispielgasse" = "example lane") so
 * nothing here can be mistaken for a real address, owner or listing.
 * Prices, features and availability are illustrative only.
 *
 * Replace this file with a real data source (CMS or database) before
 * launch. `isDemo: true` is kept on every record so the UI can render a
 * visible "DEMO" badge until real inventory exists.
 */

export const demoProperties: Property[] = [
  {
    id: "d1",
    slug: "riverside-residence-1030",
    isDemo: true,
    title: "Riverside Residence",
    listingType: "rent",
    propertyType: "apartment",
    city: "Vienna",
    district: "Landstraße",
    postalCode: "1030",
    addressLabel: "Musterstraße 12, 1030 Vienna",
    price: 1690,
    priceUnit: "month",
    size: 74,
    bedrooms: 2,
    bathrooms: 1,
    features: ["Balcony", "Elevator", "Parquet flooring", "Bike storage"],
    description:
      "A calm two-bedroom apartment close to the Donaukanal, with a south-facing balcony and an efficient, well-lit layout. Renovated kitchen, high ceilings typical of the district's Gründerzeit buildings.",
    availability: "Available from 1 November",
    images: [
      { variant: "riverside", tone: "blue", alt: "Demo building facade along a riverside street, blue tone illustration" },
      { variant: "grid", tone: "blue", alt: "Demo living room layout illustration" },
      { variant: "terrace", tone: "blue", alt: "Demo balcony illustration" },
    ],
    createdAt: "2026-08-20",
    status: "active",
  },
  {
    id: "d2",
    slug: "gruenblick-studio-1150",
    isDemo: true,
    title: "Grünblick Studio",
    listingType: "rent",
    propertyType: "studio",
    city: "Vienna",
    district: "Rudolfsheim-Fünfhaus",
    postalCode: "1150",
    addressLabel: "Beispielgasse 4, 1150 Vienna",
    price: 890,
    priceUnit: "month",
    size: 38,
    bedrooms: 1,
    bathrooms: 1,
    features: ["Courtyard view", "Fitted kitchen", "New windows"],
    description:
      "A compact, efficiently planned studio overlooking a quiet inner courtyard. Ideal for a single tenant or couple who wants low running costs without compromising on light.",
    availability: "Available now",
    images: [
      { variant: "courtyard", tone: "graphite", alt: "Demo courtyard-facing studio illustration" },
      { variant: "grid", tone: "graphite", alt: "Demo studio interior illustration" },
    ],
    createdAt: "2026-09-01",
    status: "active",
  },
  {
    id: "d3",
    slug: "belvedere-terraces-1040",
    isDemo: true,
    title: "Belvedere Terraces",
    listingType: "buy",
    propertyType: "penthouse",
    city: "Vienna",
    district: "Wieden",
    postalCode: "1040",
    addressLabel: "Musterallee 7, 1040 Vienna",
    price: 895000,
    priceUnit: "total",
    size: 128,
    bedrooms: 3,
    bathrooms: 2,
    features: ["Roof terrace", "Air conditioning", "Underground parking", "Smart home wiring"],
    description:
      "A top-floor apartment with a private roof terrace and open views toward the Belvedere gardens. New-build quality with a flexible three-room layout suited to a family or a home office setup.",
    availability: "Available from 1 December",
    images: [
      { variant: "tower", tone: "blue", alt: "Demo penthouse tower illustration" },
      { variant: "terrace", tone: "blue", alt: "Demo roof terrace illustration" },
      { variant: "grid", tone: "blue", alt: "Demo open-plan living illustration" },
    ],
    createdAt: "2026-08-05",
    status: "active",
  },
  {
    id: "d4",
    slug: "altbau-court-1070",
    isDemo: true,
    title: "Altbau Court",
    listingType: "rent",
    propertyType: "apartment",
    city: "Vienna",
    district: "Neubau",
    postalCode: "1070",
    addressLabel: "Beispielweg 21, 1070 Vienna",
    price: 1980,
    priceUnit: "month",
    size: 96,
    bedrooms: 3,
    bathrooms: 2,
    features: ["Original stucco", "Herringbone parquet", "Loggia", "Storage room"],
    description:
      "A generous three-bedroom Altbau apartment in the museum quarter, with preserved period details and a modernised bathroom. Quiet side of the building, two minutes from Neubaugasse.",
    availability: "Available from 15 October",
    images: [
      { variant: "arch", tone: "warm", alt: "Demo period building facade illustration" },
      { variant: "grid", tone: "warm", alt: "Demo period apartment interior illustration" },
    ],
    createdAt: "2026-08-28",
    status: "active",
  },
  {
    id: "d5",
    slug: "donaufeld-family-house-1210",
    isDemo: true,
    title: "Donaufeld Family House",
    listingType: "buy",
    propertyType: "house",
    city: "Vienna",
    district: "Floridsdorf",
    postalCode: "1210",
    addressLabel: "Musterhof 3, 1210 Vienna",
    price: 745000,
    priceUnit: "total",
    size: 165,
    bedrooms: 4,
    bathrooms: 2,
    features: ["Private garden", "Garage", "Basement", "Solar-ready roof"],
    description:
      "A semi-detached family house on a quiet residential street with a south-facing garden. Four bedrooms across two floors, with a garage and a basement suitable for storage or a workshop.",
    availability: "Available from 1 January",
    images: [
      { variant: "courtyard", tone: "warm", alt: "Demo family house with garden illustration" },
      { variant: "grid", tone: "warm", alt: "Demo house floor layout illustration" },
    ],
    createdAt: "2026-07-30",
    status: "active",
  },
  {
    id: "d6",
    slug: "kanalblick-loft-1020",
    isDemo: true,
    title: "Kanalblick Loft",
    listingType: "rent",
    propertyType: "loft",
    city: "Vienna",
    district: "Leopoldstadt",
    postalCode: "1020",
    addressLabel: "Beispielufer 9, 1020 Vienna",
    price: 2150,
    priceUnit: "month",
    size: 110,
    bedrooms: 2,
    bathrooms: 2,
    features: ["Double-height ceilings", "Exposed steel beams", "Floor-to-ceiling windows"],
    description:
      "A converted warehouse loft with double-height ceilings and industrial detailing, close to the Prater. Open living and kitchen area, two bedrooms, and a small home-office nook.",
    availability: "Available from 1 November",
    images: [
      { variant: "tower", tone: "graphite", alt: "Demo converted warehouse loft illustration" },
      { variant: "grid", tone: "graphite", alt: "Demo loft interior illustration" },
    ],
    createdAt: "2026-09-05",
    status: "active",
  },
  {
    id: "d7",
    slug: "schoenbrunn-edge-apartment-1120",
    isDemo: true,
    title: "Schönbrunn Edge Apartment",
    listingType: "buy",
    propertyType: "apartment",
    city: "Vienna",
    district: "Meidling",
    postalCode: "1120",
    addressLabel: "Musterplatz 5, 1120 Vienna",
    price: 415000,
    priceUnit: "total",
    size: 68,
    bedrooms: 2,
    bathrooms: 1,
    features: ["Balcony", "Elevator", "Cellar storage", "Energy-efficient windows"],
    description:
      "A well-proportioned two-bedroom apartment a short walk from Schönbrunn park, in a recently renovated building with a lift. Good starter home or investment unit.",
    availability: "Available from 1 December",
    images: [
      { variant: "grid", tone: "blue", alt: "Demo apartment building near a park illustration" },
      { variant: "terrace", tone: "blue", alt: "Demo balcony illustration" },
    ],
    createdAt: "2026-08-12",
    status: "active",
  },
  {
    id: "d8",
    slug: "nordbahn-development-1020",
    isDemo: true,
    title: "Nordbahn Development — Building C",
    listingType: "buy",
    propertyType: "new-development",
    city: "Vienna",
    district: "Leopoldstadt",
    postalCode: "1020",
    addressLabel: "Beispielallee 2, 1020 Vienna",
    price: 528000,
    priceUnit: "total",
    size: 82,
    bedrooms: 3,
    bathrooms: 2,
    features: ["New build", "Loggia", "Underfloor heating", "Shared rooftop garden"],
    description:
      "A three-room unit in a new-build development on the former Nordbahnhof grounds. Part of a wider development with a shared rooftop garden and ground-floor retail. Handover expected next year.",
    availability: "Handover Q3 2027",
    images: [
      { variant: "tower", tone: "blue", alt: "Demo new development building illustration" },
      { variant: "grid", tone: "blue", alt: "Demo new-build floor plan illustration" },
    ],
    createdAt: "2026-06-18",
    status: "active",
  },
  {
    id: "d9",
    slug: "wieden-pied-a-terre-1040",
    isDemo: true,
    title: "Wieden Pied-à-Terre",
    listingType: "rent",
    propertyType: "studio",
    city: "Vienna",
    district: "Wieden",
    postalCode: "1040",
    addressLabel: "Musterhof 15, 1040 Vienna",
    price: 950,
    priceUnit: "month",
    size: 42,
    bedrooms: 1,
    bathrooms: 1,
    features: ["Furnished option", "Fast fibre internet", "Bike storage"],
    description:
      "A tidy one-room apartment close to the Naschmarkt, suitable for a single professional. Furnished option available on request. Well connected via U-Bahn and tram.",
    availability: "Available now",
    images: [
      { variant: "courtyard", tone: "blue", alt: "Demo small apartment building illustration" },
    ],
    createdAt: "2026-09-10",
    status: "active",
  },
  {
    id: "d10",
    slug: "am-hang-house-1190",
    isDemo: true,
    title: "Am Hang House",
    listingType: "buy",
    propertyType: "house",
    city: "Vienna",
    district: "Döbling",
    postalCode: "1190",
    addressLabel: "Beispielhang 8, 1190 Vienna",
    price: 1250000,
    priceUnit: "total",
    size: 210,
    bedrooms: 5,
    bathrooms: 3,
    features: ["Hillside plot", "Terrace with view", "Wine cellar", "Double garage"],
    description:
      "A detached house on a hillside plot in Döbling with a terrace looking out over the vineyards. Five bedrooms, a wine cellar, and a double garage. Some modernisation required.",
    availability: "Available from 1 February",
    images: [
      { variant: "arch", tone: "graphite", alt: "Demo hillside house illustration" },
      { variant: "terrace", tone: "graphite", alt: "Demo terrace with view illustration" },
    ],
    createdAt: "2026-07-02",
    status: "under-offer",
  },
  {
    id: "d11",
    slug: "praterblick-apartment-1020",
    isDemo: true,
    title: "Praterblick Apartment",
    listingType: "rent",
    propertyType: "apartment",
    city: "Vienna",
    district: "Leopoldstadt",
    postalCode: "1020",
    addressLabel: "Musterweg 30, 1020 Vienna",
    price: 1450,
    priceUnit: "month",
    size: 64,
    bedrooms: 2,
    bathrooms: 1,
    features: ["Park view", "Balcony", "Elevator"],
    description:
      "A bright two-bedroom apartment on the edge of the Prater, with a balcony overlooking the treeline. Recently repainted, ready to move in.",
    availability: "Available from 1 November",
    images: [
      { variant: "riverside", tone: "warm", alt: "Demo apartment near a park illustration" },
    ],
    createdAt: "2026-09-08",
    status: "active",
  },
  {
    id: "d12",
    slug: "spittelberg-maisonette-1070",
    isDemo: true,
    title: "Spittelberg Maisonette",
    listingType: "buy",
    propertyType: "apartment",
    city: "Vienna",
    district: "Neubau",
    postalCode: "1070",
    addressLabel: "Beispielstiege 6, 1070 Vienna",
    price: 612000,
    priceUnit: "total",
    size: 88,
    bedrooms: 2,
    bathrooms: 2,
    features: ["Split-level", "Skylight", "Cobblestone street", "Cellar storage"],
    description:
      "A split-level maisonette on a cobblestone lane in Spittelberg, with a skylight bringing light into the upper bedroom. Full renovation completed last year.",
    availability: "Available from 1 December",
    images: [
      { variant: "arch", tone: "warm", alt: "Demo maisonette on a cobblestone street illustration" },
    ],
    createdAt: "2026-08-15",
    status: "active",
  },
];

export function getPropertyBySlug(slug: string): Property | undefined {
  return demoProperties.find((p) => p.slug === slug);
}
