import type { Lead, LeadStatus, ViewingRequest } from "./types";

/** DEMO data for the owner dashboard. Illustrative only — not real leads. */
export const demoLeads: Lead[] = [
  {
    id: "l1",
    name: "A. Huber",
    email: "demo.huber@example.com",
    phone: "+43 660 000 0001",
    propertyTitle: "Riverside Residence",
    status: "qualified",
    createdAt: "2026-09-10",
    notes: "Looking to move within 4 weeks. Confirmed budget by email.",
    lastContact: "2026-09-12",
    nextAction: "Offer viewing slots",
  },
  {
    id: "l2",
    name: "S. Novak",
    email: "demo.novak@example.com",
    phone: "+43 660 000 0002",
    propertyTitle: "Altbau Court",
    status: "viewing-requested",
    createdAt: "2026-09-08",
    notes: "Requested a weekend viewing.",
    lastContact: "2026-09-09",
    nextAction: "Confirm viewing time",
  },
  {
    id: "l3",
    name: "M. Berger",
    email: "demo.berger@example.com",
    phone: "+43 660 000 0003",
    propertyTitle: "Kanalblick Loft",
    status: "new",
    createdAt: "2026-09-13",
    notes: "",
    lastContact: null,
    nextAction: "First contact",
  },
  {
    id: "l4",
    name: "J. Fischer",
    email: "demo.fischer@example.com",
    phone: "+43 660 000 0004",
    propertyTitle: "Belvedere Terraces",
    status: "viewing-booked",
    createdAt: "2026-09-02",
    notes: "Viewing booked for next Thursday, 17:00.",
    lastContact: "2026-09-11",
    nextAction: "Prepare viewing",
  },
  {
    id: "l5",
    name: "R. Wagner",
    email: "demo.wagner@example.com",
    phone: "+43 660 000 0005",
    propertyTitle: "Nordbahn Development — Building C",
    status: "contacted",
    createdAt: "2026-09-05",
    notes: "Sent floor plans, awaiting reply.",
    lastContact: "2026-09-07",
    nextAction: "Follow up",
  },
  {
    id: "l6",
    name: "L. Steiner",
    email: "demo.steiner@example.com",
    phone: "+43 660 000 0006",
    propertyTitle: "Riverside Residence",
    status: "won",
    createdAt: "2026-08-20",
    notes: "Signed. Moving in November.",
    lastContact: "2026-09-01",
    nextAction: "None — closed",
  },
  {
    id: "l7",
    name: "P. Gruber",
    email: "demo.gruber@example.com",
    phone: "+43 660 000 0007",
    propertyTitle: "Am Hang House",
    status: "lost",
    createdAt: "2026-08-18",
    notes: "Chose another property.",
    lastContact: "2026-08-29",
    nextAction: "None — closed",
  },
  {
    id: "l8",
    name: "K. Wolf",
    email: "demo.wolf@example.com",
    phone: "+43 660 000 0008",
    propertyTitle: "Wieden Pied-à-Terre",
    status: "viewing-completed",
    createdAt: "2026-08-30",
    notes: "Viewed on site, deciding this week.",
    lastContact: "2026-09-06",
    nextAction: "Follow up on decision",
  },
];

export const LEAD_STATUS_LABELS: Record<LeadStatus, string> = {
  new: "New",
  contacted: "Contacted",
  qualified: "Qualified",
  "viewing-requested": "Viewing requested",
  "viewing-booked": "Viewing booked",
  "viewing-completed": "Viewing completed",
  won: "Won",
  lost: "Lost",
};

export const LEAD_PIPELINE_ORDER: LeadStatus[] = [
  "new",
  "contacted",
  "qualified",
  "viewing-requested",
  "viewing-booked",
  "viewing-completed",
  "won",
  "lost",
];

/** DEMO viewing requests, shown in the seeker account area. */
export const demoViewingRequests: ViewingRequest[] = [
  {
    id: "v1",
    propertySlug: "riverside-residence-1030",
    propertyTitle: "Riverside Residence",
    preferredDay: "2026-09-20",
    preferredTime: "Afternoon",
    message: "Would love to see the balcony in daylight if possible.",
    status: "requested",
    createdAt: "2026-09-12",
  },
];
